### PR TITLE
Nintendo64 theme

### PR DESCRIPTION
**Pull request by byt3smith**
screen shot 2016-05-31 at 3 58 12 pm

### CODE REVIEW

**Comment by byt3smith** [comment]
Apparently not a lot of Nintendo fans out there. Closing

**Comment by Brottweiler** [comment]
@byt3smith You got 2 "unsure" reactions. Most themes, if not all, seem to get accepted, and there's a bunch of "ugly" themes out there anyway which I like (see Amiga and Windows 95). The problem I have with yours is that neon blue on neon green... is just an eyesore. I am all for a "N64 theme", but with tweaked colors. 

That's just my opinion, and I am not against adding this theme. Whoever does not like it, can just not use it.

**Comment by byt3smith** [comment]
@Brottweiler Yeah, the contrast is a bit stark. I use it in one of my teams and like it a lot, but I was trying to keep close to the original shades of the n64 logo, though it doesn't necessarily translate perfectly to a theme.

**Comment by paracycle** [comment]
Yeah, I generally am not too selective on themes and tend to accept all that comes this way. However, this one made me pause and think before I decided on it. And exactly for the reasons @Brottweiler outlined in his comment. I have nothing against an N64 Theme, but if the harmony of colors work out better, it would be much more pleasing to all.

**Comment by byt3smith** [comment]
Absolutely. Thanks @paracycle, @Brottweiler, Will consider that for any future themes

**Comment by byt3smith** [comment]
something like this might be a little better
screen shot 2016-06-01 at 10 04 51 am

**Comment by Brottweiler** [comment]
@byt3smith Way beter, but I think you forgot(?) to change the red and/or yellow, although I never mentioned those colors specifically, I think they also are too strong.

**Comment by byt3smith** [comment]
Hmm, yeah, the red does stand out.

How about that?

screen shot 2016-06-01 at 10 18 29 am

**Comment by Brottweiler** [comment]
I think that looks pretty good, I approve! 👍

**Pull request closed without merging**
