### PR TITLE
adding Github theme

### PR DESCRIPTION
**Pull request by gabrielboliveira**
Simple Github theme based on its website.

### CODE REVIEW

**Comment by paracycle** [comment]
Hey @gabrielboliveira, thank you so much for this contribution, but I don't think the colors properly represent Github. Do you mind changing this so that the implication is more explicit and the result is more readable? Thanks

**Comment by gabrielboliveira** [comment]
@paracycle For sure I submitted this PR before Github changes. I'll work on the colors again and update this PR.

**Comment by gabrielboliveira** [comment]
@paracycle I've messed up this branch, sorry about that. I've opened a new clean PR: #146

**Comment by paracycle** [comment]
No worries

**Pull request closed without merging**
