### PR TITLE
Add "Material Indigo" theme

### PR DESCRIPTION
**Pull request by xiprox**
Red:

Pink:

Purple:

Deep Purple:

Indigo:

Blue:

Light Blue:

Yellow:

Amber:

Orange:

Deep Orange:

Brown:

### CODE REVIEW

**Comment by paracycle** [comment]
Thanks, this is great work. However, I don't want to create a whole section of Material themes in the repository, if feels too overwhelming.

Having said that, I have 2 suggestions:

1. I can pick one more light theme and dark versions of the same. We already have the Blue Gray, so can you pick your second most favorite? I'll pick the dark versions of the same from #60.
2. Maybe you and @wopian might want to build a quick Material Slack Themes generator :smile:. I'll link to it and if you want can help you do it as well. Might be interesting on its own.

**Comment by xiprox** [comment]
Oh, I see. Totally makes sense.

Well, Indigo sounds good to me. You can go with that, I guess.

@wopian is already on it. He should have something done real soon.

**Comment by wopian** [comment]
@paracycle, how do I go about triggering the gh-pages build? Travis is outputting identical logs, but am I missing something else within the repo?

**Comment by paracycle** [comment]
@wopian You'll need to setup the encrypted credentials in the [Travis file](https://github.com/wopian/material-slackthemes/blob/master/.travis.yml#L10) to match your credentials (or set them from the Travis UI as build parameters) so that a Travis build can push to your repo.

**Comment by wopian** [comment]
@paracycle ah forgot about that, what's the `GIT_NAME` in reference too? ...because I have no idea. :sob:

**Pull request merged**
