### PR TITLE
Add theme for the Github contribution graph

### PR DESCRIPTION
**Pull request by IgorAntun**

### CODE REVIEW

**Comment by IgorAntun** [comment]
RIP?

**Comment by paracycle** [comment]
Hey @IgorAntun, no the project is not RIP, I've just not been able to spend any time on this recently. I'll look into all the pending PRs next week. Thanks for the reminder.

**Comment by IgorAntun** [comment]
Sure, thanks :)

**Comment by IgorAntun** [comment]
Sorry for bothering, but any updates so far?

**Comment by IgorAntun** [comment]
...

**Pull request merged**
