### PR TITLE
Adding in Solarized, for your pleasure

### PR DESCRIPTION
**Pull request by joelgriffith**
Quick'n'dirty Solarized theme.

### CODE REVIEW

**Comment by joebadmo** [comment]
+1

**Comment by joelgriffith** [comment]
NM, apparently this was added to the site already, but the maintainer hasn't pushed to GH yet :cry:

**Comment by paracycle** [comment]
That's strange since I can see it on the site: http://slackthemes.net/#/solarized

AFAICS, it's been on the site for a long time (even the Dark variant). Actually, if you look closely, the Solarized theme is there even before the change that this PR introduces?!

**Comment by joelgriffith** [comment]
You are correct! I wonder how I missed it when I initially found the site.

In either case, very good!

**Comment by paracycle** [comment]
Hey, all is good. Thanks a lot for taking the time to contribute.

**Pull request closed without merging**
