### PR TITLE
Add New Themes and sort YML file script

### PR DESCRIPTION
**Pull request by lacostenycoder**

### CODE REVIEW

**Comment by paracycle** [comment]
Hey, I appreciate the theme submission but I won't be able to accept this PR as is. I don't intend to sort the themes in the file, especially in a PR that has unrelated changes. Maybe you can split your changes into 2 PRs, one that adds new themes and another that sorts the YAML file and give a good enough reason for it to be sorted.

**Comment by paracycle** [comment]
BTW, the sorting routine is misguided. The data file is a structured entity in YAML format but you are sorting it as if it is a simple text file, which won't always give the correct results. Not surprisingly, the change breaks the build.

**Comment by lacostenycoder** [comment]
OK, no problem.  Sorting is not really needed as it appears to happen on the middleman build anyway so I'll remove sort and just submit new PR with new themes only.

**Comment by paracycle** [comment]
Thanks

**Comment by lacostenycoder** [comment]
Just wondering why sorting the yaml file breaks in travis.  How should I be adding new themes?

**Comment by paracycle** [comment]
I've looked into that and the problem wasn't related to the sorting but to a mistaken `.` where a `,` should have been: https://github.com/paracycle/slackthemes/pull/84/files#diff-f6fea98cc4ca00f37a1136635a8d9ab3R67

Never mind the sorting, just add the new themes at the end of the file. :)

**Pull request closed without merging**
