### PR TITLE
adding Dolly theme

### PR DESCRIPTION
**Pull request by kelbyhawn**

### CODE REVIEW

**Comment by paracycle** [comment]
Hey @kelbyhawn thanks for the PR. I would like to merge this but don't you think this is awfully similar to the [Base 16 Eighties Light](http://slackthemes.net/#/base16_eighties_light) theme?

**Comment by kelbyhawn** [comment]
Hi @paracycle! I made this for my team at Dolly (https://dolly.com). I agree the color scheme is similar, but Base16 has a beige base, less saturated colors, and looks more feminine.

**Comment by paracycle** [comment]
Ok you convinced me... :) Thanks again.

**Comment by kelbyhawn** [comment]
Awesome, thanks! :smile:

**Pull request merged**
